# docker-compose.yml
version: "3.8"

services:
  # Next.js Application
  app:
    build: .
    container_name: sate-jip-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:your_secure_password@db:3306/sate_jip_db
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: sate-jip-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678Haha # Change this
      MYSQL_DATABASE: sate_jip_db
      MYSQL_USER: sate_jip_user
      MYSQL_PASSWORD: 12345678Haha # Change this
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sate-jip-pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 12345678Haha # Same as MYSQL_ROOT_PASSWORD
    depends_on:
      - db
  adminer:
    image: adminer
    container_name: sate-jip-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
