# docker-compose.dev.yml (Development)
# Gunakan perintah: docker compose -f docker-compose.dev.yml up

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Kita bisa tetap pakai Dockerfile utama
      target: builder # Hanya build sampai tahap 'builder'
    container_name: sate-jip-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules # Mencegah node_modules lokal menimpa yang di container
      - /app/.next # Cache untuk build development
    command: npm run dev
    networks:
      - sate-jip-network

networks:
  sate-jip-network:
    driver: bridge
