# docker-compose.yml

services:
  # Next.js Application
  app:
    build: .
    container_name: sate-jip-app-diskominfo
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    # depends_on:
    #   - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
